### ISSUE TITLE
Unexpected number of collected bytes in pause/resume after multiple runs

### ISSUE THREAD

**Issue by ganesh-k13** [mkirchner/gc#50] opened 2020-01-20 04:51 UTC
When I run the test multiple times, TC 11 fails sometimes: https://gist.github.com/ganesh-k13/62d7745e94df42d579dc05faf05db6f3
system info:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
```

**Comment by mkirchner** [comment] 2020-11-14 19:09
@ganesh-k13 , is this still an issue? I cannot reproduce and am close the issue for now. We can reopen if/when required.

**Closed by mkirchner** 2020-11-14 19:09 UTC
