### ISSUE TITLE
Memory leak in Windows and VS2010

### ISSUE THREAD

**Issue by ssrlive** [mkirchner/gc#14] opened 2019-12-23 06:09 UTC
I change the `main` function like this:
```
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>

#define MEM_CHECK_BEGIN() do { _CrtSetDbgFlag( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF ); } while(0)
#define MEM_CHECK_DUMP_LEAKS() do { _CrtDumpMemoryLeaks(); } while(0)

int main()
{
    char *result;
    MEM_CHECK_BEGIN();

    result = test_suite();
    if (result) {
        printf("%s\n", result);
    } else {
        printf("ALL TESTS PASSED\n");
    }
    printf("Tests run: %d\n", tests_run);

    MEM_CHECK_DUMP_LEAKS();
    return result != 0;
}
```
and the debugger report memory leaking.

**Comment by mkirchner** [comment] 2019-12-23 07:09
Thanks for reporting this. I don't have access to a windows machine and hence cannot reproduce. Is there any way how you can narrow this down, possibly into a PR? I'll also add a help wanted tag to this.

**Comment by mkirchner** [comment] 2019-12-23 07:11
Removed the bug label until we know for sure that it's not just a leak in the test harness :)

**Comment by ssrlive** [comment] 2019-12-23 07:13
```
'gc.exe': Loaded 'C:\Users\Administrator\Desktop\gc\Debug\gc.exe', Symbols loaded.
'gc.exe': Loaded 'C:\Windows\SysWOW64\ntdll.dll', Cannot find or open the PDB file
'gc.exe': Loaded 'C:\Windows\SysWOW64\kernel32.dll', Cannot find or open the PDB file
'gc.exe': Loaded 'C:\Windows\SysWOW64\KernelBase.dll', Cannot find or open the PDB file
'gc.exe': Loaded 'C:\Windows\SysWOW64\msvcr100d.dll', Symbols loaded.
Detected memory leaks!
Dumping objects ->
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1919} normal block at 0x011A57E0, 4124 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1918} normal block at 0x011A5770, 48 bytes long.
 Data: <               ?> 07 04 00 00 07 04 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1853} normal block at 0x011A4718, 4124 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1852} normal block at 0x011A46A8, 48 bytes long.
 Data: <               ?> 07 04 00 00 07 04 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1339} normal block at 0x011A45D8, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1338} normal block at 0x011A4568, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {311} normal block at 0x011A4498, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {310} normal block at 0x011A4428, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {275} normal block at 0x011A4280, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {274} normal block at 0x011A4210, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(331) : {270} normal block at 0x011A43E8, 4 bytes long.
 Data: <    > 05 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(331) : {268} normal block at 0x011A4350, 8 bytes long.
 Data: < C      > E8 43 1A 01 00 00 00 00 
test\test_gc.c(92) : {68} normal block at 0x011A41D0, 4 bytes long.
 Data: <    > 05 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {67} normal block at 0x011A4150, 68 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {66} normal block at 0x011A40E0, 48 bytes long.
 Data: <               ?> 11 00 00 00 0B 00 00 00 9A 99 99 99 99 99 C9 3F 
Object dump complete.
The thread 'Win32 Thread' (0x1424) has exited with code 0 (0x0).
The thread 'Win32 Thread' (0x140c) has exited with code 0 (0x0).
Detected memory leaks!
Dumping objects ->
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1919} normal block at 0x011A57E0, 4124 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1918} normal block at 0x011A5770, 48 bytes long.
 Data: <               ?> 07 04 00 00 07 04 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1853} normal block at 0x011A4718, 4124 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1852} normal block at 0x011A46A8, 48 bytes long.
 Data: <               ?> 07 04 00 00 07 04 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {1339} normal block at 0x011A45D8, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {1338} normal block at 0x011A4568, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {311} normal block at 0x011A4498, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {310} normal block at 0x011A4428, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {275} normal block at 0x011A4280, 148 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {274} normal block at 0x011A4210, 48 bytes long.
 Data: <%   %          ?> 25 00 00 00 25 00 00 00 9A 99 99 99 99 99 C9 3F 
c:\users\administrator\desktop\gc\test\../src/gc.c(331) : {270} normal block at 0x011A43E8, 4 bytes long.
 Data: <    > 05 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(331) : {268} normal block at 0x011A4350, 8 bytes long.
 Data: < C      > E8 43 1A 01 00 00 00 00 
test\test_gc.c(92) : {68} normal block at 0x011A41D0, 4 bytes long.
 Data: <    > 05 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(158) : {67} normal block at 0x011A4150, 68 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
c:\users\administrator\desktop\gc\test\../src/gc.c(150) : {66} normal block at 0x011A40E0, 48 bytes long.
 Data: <               ?> 11 00 00 00 0B 00 00 00 9A 99 99 99 99 99 C9 3F 
Object dump complete.
The program '[5756] gc.exe: Native' has exited with code 0 (0x0).

```

**Comment by mkirchner** [comment] 2019-12-23 07:14
Thanks! Is this related to #13 ?

**Comment by ssrlive** [comment] 2019-12-23 07:16
![image](https://user-images.githubusercontent.com/30760636/71342234-20467800-2597-11ea-893e-a9dc17c3bd7b.png)

**Comment by ssrlive** [comment] 2019-12-23 07:17
> Thanks! Is this related to #13 ?

No, #13 is just a crash fixing.

**Comment by ssrlive** [comment] 2019-12-23 07:19
![image](https://user-images.githubusercontent.com/30760636/71342379-8fbc6780-2597-11ea-8512-ee2bca6f8dda.png)

**Comment by ssrlive** [comment] 2019-12-23 07:25
Is your global object have a memory allocate? Maybe it is for this reason.

**Comment by mkirchner** [comment] 2019-12-23 07:30
The definition of `gc_mcalloc()` in the `master` branch looks different, see [here](https://github.com/mkirchner/gc/blob/dc4ac3f4c42940e3e85fb24ebb01a24898ad68c1/src/gc.c#L322). If the `count` is zero, `gc_mcalloc()` defers to `malloc()`.

I don't want to suggest that there is no bug/mem leak but are you sure you're using the correct version of the code?

**Comment by ssrlive** [comment] 2019-12-23 07:36
VS2010 shiped C89 compiler. so I have to make some change.

I'm using c89 standard instead of c99, can you change the code to fit C89?

**Comment by mkirchner** [comment] 2019-12-23 08:02
Aww, sorry to hear - that sounds quite painful.

What I am hearing is that (a) you're running on Windows which really was not the target platform for this toy project; and (b) you're (sadly) forced to use a different version of the C language standard.

I'd be super happy to have someone other than me work on Windows support but supporting C89 seems like a lot of questionable effort.

Is there any way for you to upgrade to VS2015? Since C++11 includes *nearly* all of C99, that would probably be the easiest solution?

**Comment by ssrlive** [comment] 2019-12-23 08:08
Test it with ubuntu and Valgrind. it seems that REAL leaked. this time the code not changed.

![Screenshot from 2019-12-23 16-04-24](https://user-images.githubusercontent.com/30760636/71344676-2db33080-259e-11ea-9a36-55172c96dc25.png)

**Comment by mkirchner** [comment] 2019-12-23 08:14
Thanks! That was helpful. See here: #16.

**Comment by ssrlive** [comment] 2019-12-23 08:49
![Screenshot from 2019-12-23 16-47-11](https://user-images.githubusercontent.com/30760636/71346972-3444a680-25a4-11ea-8467-2c856cf888e7.png)

**Comment by mkirchner** [comment] 2019-12-24 05:48
was this fixed with #21?

**Comment by ssrlive** [comment] 2019-12-24 05:53
no. i find that all the rest of the tests exist leaks.
```
static char* test_suite()
{
    printf("---=[ GC tests\n");
    mu_run_test(test_gc_allocation_new_delete);
    mu_run_test(test_gc_allocation_map_new_delete);
    mu_run_test(test_gc_allocation_map_basic_get);
    mu_run_test(test_gc_allocation_map_put_get_remove);
//    mu_run_test(test_gc_mark_stack);
//    mu_run_test(test_gc_basic_alloc_free);
//    mu_run_test(test_gc_allocation_map_cleanup);
//    mu_run_test(test_gc_static_allocation);
//    mu_run_test(test_primes);
//    mu_run_test(test_gc_pause_resume);
//    mu_run_test(test_gc_strdup);
    return 0;
}
```
the first 4 items are OK.

**Comment by mkirchner** [comment] 2019-12-24 06:43
So, I ran valgrind on OSX High Sierra and this is what I get:

```
==56476== LEAK SUMMARY:
==56476==    definitely lost: 0 bytes in 0 blocks
==56476==    indirectly lost: 0 bytes in 0 blocks
==56476==      possibly lost: 72 bytes in 3 blocks
==56476==    still reachable: 200 bytes in 6 blocks
==56476==         suppressed: 22,181 bytes in 154 blocks
```
where the 72  "possibly" lost bytes come from OSX-internal mach loading.

**Comment by ssrlive** [comment] 2019-12-24 06:46
In windows, there only `mu_run_test(test_gc_mark_stack);` leaked, all the others are OK, not leak.

**Comment by mkirchner** [comment] 2019-12-24 06:48
Can you share the leak report here? (Text format would be great)

**Comment by mkirchner** [comment] 2019-12-24 06:49
Oh, and side comment, I added a few missing calls to `free` and initializations in #23 .

**Comment by ssrlive** [comment] 2019-12-24 06:52
![image](https://user-images.githubusercontent.com/30760636/71398929-ffe0f100-265c-11ea-816c-8676a9499214.png)

**Comment by ssrlive** [comment] 2019-12-24 07:23
> Oh, and side comment, I added a few missing calls to `free` and initializations in #23 .

after this patch, all the leaks disappear in windows.

**Closed** 2019-12-25 01:40 UTC
Labels: help wanted
